# Generated by Django 6.0.3 on 2026-03-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
