# Generated by Django 6.0.3 on 2026-03-07 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.course'),
        ),
    ]
