# Generated by Django 6.0.3 on 2026-03-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_students_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course',
        ),
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.ManyToManyField(null=True, to='students.course'),
        ),
    ]
