# Generated by Django 6.0.3 on 2026-03-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_students_course_students_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.ManyToManyField(null=True, related_name='courses', to='students.course'),
        ),
    ]
