# Generated by Django 6.0.3 on 2026-03-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_students_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.ManyToManyField(null=True, to='students.course'),
        ),
    ]
